### ISSUE TITLE
Update Maintainer and attribution

### ISSUE THREAD

**Issue by javahippie** [operaton/operaton-keycloak#1]
At the end of the README, maintainers and their companies are still mentioned. This could be confusing for users and annoying for the maintainers of the original Camunda Keycloak plugin.

**Comment by hauptmedia** [comment]
I'm also thinking about informing the original maintainer that we forked his repo

**Comment by javahippie** [comment]
I have met Gunnar and he is a really nice guy, would be fair to give him notice 👍
