### ISSUE TITLE
Use Testcontainers for Keycloak tests

### ISSUE THREAD

**Issue by kthoms** [operaton/operaton-keycloak#10]
**Is your feature request related to a problem? Please describe.**
The tests expect that a Keycloak server is running. With docker compose it is easy to set it up. Anyways, the tests should not assume that a Keycloak is already running on a fixed port.

**Describe the solution you'd like**
Set up the tests to use Testcontainers.

**Comment by javahippie** [comment]
Might overlap with https://github.com/operaton/operaton-keycloak/issues/3
