### ISSUE TITLE
Update Keycloak in the GitHub workflow to the most recent version

### ISSUE THREAD

**Issue by hauptmedia** [operaton/operaton-keycloak#17]
**Is your feature request related to a problem? Please describe.**

The tests are currently running against keycloak version 19.0.3 which is totally outdated.

**Describe the solution you'd like**
 It should be updated to version 26.0.7.

**Additional context**
There is already a valid config for testing against 26.0.7 in the docker-compose.yml. We just have to copy these settings into the github workflow

**Comment by hauptmedia** [comment]
An alternative approach is using Testcontainers, which is something @kthoms is already working on, so perhaps this issue becomes obsolete then

**Comment by kthoms** [comment]
I expect that this should become obsolete

**Comment by kthoms** [comment]
But... Is it of interest to test against different Keycloak versions? I think this likely makes sense. The workflow could test against a defined list of Keycloak versions. If so, please provide a list.

**Comment by hauptmedia** [comment]
Running an outdated version of Keycloak is not recommended, as outlined here: https://endoflife.date/keycloak.

As a security-focused product that has been essentially feature-complete for several versions, it’s crucial to always stay updated to the latest version. There was a major breaking change when they changed their Wildfly Distribution to Quarkus, but I think this was already 3 years ago.

**Comment by hauptmedia** [comment]
there is actually a LTS release by Red Hat, but i'm not aware of anybody who uses it. See this comment https://github.com/keycloak/keycloak/discussions/25688#discussioncomment-10461280

**Comment by kthoms** [comment]
I have removed the Keycloak reference from the workflows. This became obsolete via #10 .
