### ISSUE TITLE
Set up Sonarqube

### ISSUE THREAD

**Issue by kthoms** [operaton/operaton-keycloak#24]
**Is your feature request related to a problem? Please describe.**
It should be assured that the code quality matches certain criteria and pull requests do not violate that.

**Describe the solution you'd like**
Integrate static code analysis in the build process. Fail a PR build when requirements are not met.

The Operaton main repo already uses [Sonarqube](https://www.sonarsource.com/plans-and-pricing/sonarcloud/) for this. This should be set up for this project, too.

**Comment by javahippie** [comment]
Should be already done for some time now: https://sonarcloud.io/project/overview?id=operaton_operaton-keycloak

**Comment by kthoms** [comment]
My bad. Then I'll just add the badge.
