### ISSUE TITLE
Tests failing with `Unable to get access token from Keycloak server`

### ISSUE THREAD

**Issue by kthoms** [operaton/operaton-keycloak#8]
Tests are failing
```
Tests in error: 
  testFilterByGroupNameAndGroupNameLike(org.operaton.bpm.extension.keycloak.test.KeycloakGroupQueryTest): Unable to get access token from Keycloak server
  testQueryPaging(org.operaton.bpm.extension.keycloak.test.KeycloakGroupQueryTest): Unable to get access token from Keycloak server
  testFilterByGroupId(org.operaton.bpm.extension.keycloak.test.KeycloakGroupQueryTest): Unable to get access token from Keycloak server
  ...
```

see [build log](https://github.com/operaton/operaton-keycloak/actions/runs/12187089423/job/33997069380).

**Steps to reproduce**

```
docker compose up -d
./mvnw
```

**Comment by hauptmedia** [comment]
This should be fixed by 18997bd and ea5f075 now. If you can confirm it, please close the issue

**Comment by kthoms** [comment]
Locally I still get this, but I see that the build on `master` succeeds. I have to investigate why I have problems. Likely they are local, and the issue should be fixed.

**Comment by kthoms** [comment]
When I run Maven from IJ, then it succeeds. I get still get the problem when executing `./mvnw verify`. Both should execute the same build, but there is some subtle difference which I have to figure out.

**Comment by hauptmedia** [comment]
Perhaps it has something to do with the ENV vars => https://github.com/operaton/operaton-keycloak/blob/master/README.md#maven-test-setup (but i have not set them up, i think their defaults match to the settings in the docker-compose file)
Or you need to `docker-compose rm` the whole stack. For me it's running fine with  `./mvnw verify`

**Comment by kthoms** [comment]
It seemed to be a problem with the shell. I ran in iTerm and it works. So yes, the problem is solved.
